module.exports = ["TOKYO, Japan",
"JAKARTA, Indonesia",
"New York (NY), United States",
"SEOUL, South Korea",
"MANILA, Philippines",
"Mumbai (Bombay), India",
"Sao Paulo, Brazil",
"MEXICO CITY, Mexico",
"Delhi, India",
"Osaka, Japan",
"CAIRO, Egypt",
"Kolkata (Calcutta), India",
"Los Angeles (CA), United States",
"Shanghai, China",
"MOSCOW, Russia",
"BEIJING (PEKING), China",
"BUENOS AIRES, Argentina",
"Guangzhou, China",
"Shenzhen, China",
"Istanbul, Turkey",
"Rio de Janeiro, Brazil",
"PARIS, France",
"Karachi, Pakistan",
"Nagoya, Japan",
"Chicago (IL), United States",
"Lagos, Nigeria",
"LONDON, United Kingdom",
"BANGKOK, Thailand",
"KINSHASA, Dem Rep of Congo ",
"TEHRAN, Iran",
"LIMA, Peru",
"Dongguan, China",
"BOGOTA, Colombia",
"Chennai (Madras), India",
"DHAKA, Bangladesh",
"Essen, Germany",
"Tianjin (Tientsin), China",
"HONG KONG, China - Hong Kong",
"Taipei, Taiwan (China ROC)",
"Lahore, Pakistan",
"Ho Chi Minh City (Saigon), Viet Nam",
"Bangalore, India",
"Hyderabad, India",
"Johannesburg, South Africa",
"BAGHDAD, Iraq",
"Toronto, Canada",
"SANTIAGO, Chile",
"KUALA LUMPUR, Malaysia",
"San Francisco (CA), United States",
"Philadelphia (PA), United States",
"Wuhan, China",
"Miami (FL), United States",
"Dallas (TX), United States",
"MADRID, Spain",
"Ahmedabad, India",
"Boston (MA), United States",
"Belo Horizonte, Brazil",
"KHARTOUM, Sudan",
"Saint Petersburg (Leningrad), Russia",
"Shenyang, China",
"Houston (TX), United States",
"Pune, India",
"RIYADH, Saudi Arabia",
"SINGAPORE, Singapore",
"WASHINGTON (DC), United States",
"Yangon , Myanmar ",
"Milan (Milano), Italy",
"Atlanta (GA), United States",
"Chongqing, China",
"Alexandria, Egypt",
"Nanjing (Nanking) , China",
"Guadalajara, Mexico",
"Barcelona, Spain",
"Chengdu, China",
"Detroit (MI), United States",
"ANKARA, Turkey",
"Abidjan, Côte d'Ivoire",
"ATHENS, Greece",
"BERLIN, Germany",
"Sydney, Australia",
"Monterrey, Mexico",
"Phoenix (AZ), United States",
"Busan (Pusan), South Korea",
"Recife, Brazil",
"Bandung, Indonesia",
"Porto Alegre, Brazil",
"Melbourne, Australia",
"LUANDA, Angola",
"Hangzhou (Hangchow) , China",
"ALGIERS, Algeria",
"Hà Noi (HANOI), Viet Nam",
"Montréal, Canada",
"Xi'an (Sian) , China",
"PYONGYANG, North Korea",
"Qingdao (Tsingtao) , China",
"Surat, India",
"Fortaleza, Brazil",
"Medellín, Colombia",
"Durban, South Africa",
"Kanpur, India",
"ADDIS ABABA, Ethiopia",
"NAIROBI, Kenya",
"Jeddah (Jiddah), Saudi Arabia",
"Naples (Napoli), Italy",
"KABUL, Afghanistan",
"Salvador, Brazil",
"Harbin (Haerbin), China",
"Kano, Nigeria",
"Casablanca (Dar-el-Beida), Morocco",
"CAPE TOWN, South Africa",
"Curitiba, Brazil",
"Surabaya, Indonesia",
"San Diego (CA), United States",
"Seattle (WA), United States",
"ROME, Italy",
"Dar es Salaam, Tanzania",
"Taichung, China",
"Jaipur, India",
"CARACAS, Venezuela",
"DAKAR, Senegal",
"Kaohsiung, China",
"Minneapolis (MN), United States",
"Lucknow, India",
"AMMAN, Jordan",
"Tel Aviv-Yafo, Israel",
"Guayaquil, Ecuador",
"KYIV (KIEV), Ukraine",
"Faisalabad (Lyallpur), Pakistan",
"Mashhad, Iran",
"Izmir, Turkey",
"Rawalpindi, Pakistan",
"TASHKENT, Uzbekistan",
"Katowice, Poland",
"Changchun, China",
"Campinas, Brazil",
"Daegu (Taegu), South Korea",
"Changsha, China",
"Nagpur, India",
"San Juan, Philippines",
"Aleppo, Syria",
"LISBON, Portugal",
"Frankfurt am Main, Germany",
"Nanchang, China",
"Birmingham[] , United Kingdom ",
"Tampa (FL), United States",
"Medan, Indonesia",
"Dalian, China",
"TUNIS, Tunisia",
"Shijiazhuang, China",
"Manchester, United Kingdom",
"PORT-AU-PRINCE, Haiti",
"DAMASCUS, Syria",
"Ji'nan, China",
"Fukuoka, Japan",
"SANTO DOMINGO, Dominican Republic",
"HAVANA, Cuba",
"Cali, Colombia",
"Denver (CO), United States",
"St. Louis (MO), United States",
"Colombo, Brazil",
"Dubai, United Arab Emirates",
"Baltimore (MD), United States",
"Sapporo, Japan",
"Rotterdam, Netherlands",
"Vancouver, Canada",
"Preston, United Kingdom",
"Patna, India",
"SANA'A, Yemen",
"WARSAW, Poland",
"Bonn, Germany",
"ACCRA, Ghana",
"BUCHAREST, Romania",
"Yokohama, Japan",
"Kunming, China",
"Guiyang, China",
"Zibo, China",
"Incheon, South Korea",
"Zhengzhou, China",
"Taiyuan, China",
"Chaoyang (Guangdong), China",
"BRASILIA, Brazil",
"Zhongshan, China",
"West Midlands, United Kingdom",
"Giza, Egypt",
"Quezon City, Philippines",
"Nanhai, China",
"Fuzhou (Fujian), China",
"Lanzhou, China",
"Xiamen, China",
"Chittagong, Bangladesh",
"Zaozhuang, China",
"Jilin, China",
"Linyi, China",
"Wenzhou, China",
"STOCKHOLM, Sweden",
"Puebla de Zaragoza, Mexico",
"Puning, China",
"BAKU, Azerbaijan",
"Ibadan, Nigeria",
"Brisbane, Australia",
"MINSK, Belarus",
"Sikasso, Mali",
"Nanchong, China",
"Nanning, China",
"Urumqi, China",
"Yantai, China",
"Fuyang (Zhejiang), China",
"Tangshan, China",
"Maracaibo, Venezuela",
"Hamburg, Germany",
"BUDAPEST, Hungary",
"Shunde, China",
"Manaus, Brazil",
"Xuzhou, China",
"Ségou, Mali",
"Baotou, China",
"Hefei, China",
"VIENNA, Austria",
"Indore, India",
"ASUNCION, Paraguay",
"Tianmen, China",
"BELGRADE, Serbia",
"Suzhou (Anhui), China",
"Suizhou, China",
"Nanyang, China",
"Nakuru, Kenya",
"Koulikoro, Mali",
"Ningbo, China",
"Liuan, China",
"Anshan, China",
"Tengzhou, China",
"Qiqihaer, China",
"Pizhou, China",
"Taian, China",
"Datong, China",
"Kobe, Japan",
"Hama, Syria",
"Esfahan, Iran",
"TRIPOLI, Libya",
"West Yorkshire, United Kingdom",
"Vadodara, India",
"Taizhou (Zhejiang), China",
"Luoyang, China",
"QUITO, Ecuador",
"Jinjiang, China",
"Mopti, Mali",
"Perth, Australia",
"Daejeon (Taejon), South Korea",
"Kyoto, Japan",
"Xiantao, China",
"Tangerang, Indonesia",
"Bhopal, India",
"Coimbatore, India",
"Kharkiv, Ukraine",
"Gwangju (Kwangchu), South Korea",
"Xinghua, China",
"HARARE, Zimbabwe",
"Fushun, China",
"Shangqiu, China",
"Belém, Brazil",
"Wuxi, China",
"Hechuan, China",
"Wujin, China",
"Guigang, China",
"Jianyang (Sichuan), China",
"Huhehaote, China",
"Santa Cruz, Bolivia",
"Semarang, Indonesia",
"Ludhiana, India",
"Novosibirsk, Russia",
"Neijiang, China",
"MAPUTO, Mozambique",
"Nan'an, China",
"Douala, Cameroon",
"Weifang, China",
"Daqing, China",
"Kayes, Mali",
"Tongzhou, China",
"Tabriz, Iran",
"Homs, Syria",
"Rugao, China",
"Guiping, China",
"Huainan, China",
"Kochi, India",
"Suining, China",
"Bozhou, China",
"Zhanjiang, China",
"Changde, China",
"MONTEVIDEO, Uruguay",
"Suzhou (Jiangsu), China",
"Xintai, China",
"Ekaterinoburg, Russia",
"Juárez, Mexico",
"Handan, China",
"Visakhapatnam, India",
"Kawasaki, Japan",
"Jiangjin, China",
"Pingdu, China",
"Agra, India",
"Jiangyin, China",
"Tijuana, Mexico",
"Liuyang, China",
"Bursa, Turkey",
"Al-Hasakeh, Syria",
"Makkah, Saudi Arabia",
"YAOUNDE, Cameroon",
"Xuanwei, China",
"Dengzhou, China",
"Palembang, Indonesia",
"Nizhny Novgorod, Russia",
"León (de los Aldama), Mexico",
"Guarulhos, Brazil",
"Heze, China",
"Auckland, New Zealand",
"Omdurman, Sudan",
"Shantou, China",
"Leizhou, China",
"Yongcheng, China",
"Valencia, Venezuela",
"Thane, India",
"San Antonio (TX), United States",
"Xinyang, China",
"Luzhou, China",
"Almaty, Kazakhstan",
"Changshu, China",
"Taixing, China",
"PHNOM PENH, Cambodia",
"Laiwu, China",
"Xiaoshan, China",
"Yiyang, China",
"Goiânia, Brazil",
"Liuzhou, China",
"Gaozhou, China",
"Fengcheng (Jiangxi), China",
"Cixi, China",
"Karaj, Iran",
"MOGADISHU, Somalia",
"Varanasi, India",
"Córdoba, Argentina",
"KAMPALA, Uganda",
"Ruian, China",
"Lianjiang, China",
"Huaian, China",
"Shiraz, Iran",
"Multan, Pakistan",
"Madurai, India",
"München, Germany",
"Kalyan, India",
"Quanzhou, China",
"Adana, Turkey",
"Bazhong, China",
"Fès, Morocco",
"OUAGADOUGOU, Burkina Faso",
"Haicheng, China",
"Xishan, China",
"Leiyang, China",
"Caloocan, Philippines",
"Kalookan (Caloocan), Philippines",
"Jingzhou, China",
"Saitama, Japan",
"PRAGUE, Czech Republic",
"Fuqing, China",
"Kumasi, Ghana",
"Meerut, India",
"Hyderabad, Pakistan",
"Lufeng, China",
"Dongtai, China",
"Yixing, China",
"Mianyang, China",
"Wenling, China",
"Leqing, China",
"OTTAWA, Canada",
"Yushu, China",
"Barranquilla, Colombia",
"Hiroshima, Japan",
"Chifeng, China",
"Nashik, India",
"Makasar (Ujung Pandang), Indonesia",
"SOFIA, Bulgaria",
"Rizhao, China",
"Davao, Philippines",
"Tianshui, China",
"Huzhou, China",
"Samara (Samarskaya oblast), Russia",
"Omsk, Russia",
"Gujranwala, Pakistan",
"Adelaide, Australia",
"Macheng, China",
"Wuxian, China",
"Bijie, China",
"Yuzhou, China",
"Leshan, China",
"La Matanza, Argentina",
"Rosario, Argentina",
"Jabalpur, India",
"Kazan, Russia",
"Jimo, China",
"Dingzhou, China",
"Calgary, Canada",
"YEREVAN, Armenia",
"El-Jadida, Morocco",
"Jamshedpur, India",
"Zürich, Switzerland",
"Zoucheng, China",
"Pikine-Guediawaye, Senegal",
"Anqiu, China",
"Guang'an, China",
"Chelyabinsk, Russia",
"CONAKRY, Guinea",
"Asansol, India",
"Shouguang, China",
"Changzhou, China",
"Ulsan, South Korea",
"Zhuji, China",
"Toluca (de Lerdo), Mexico",
"Marrakech, Morocco",
"Dhanbad, India",
"TBILISI, Georgia",
"Hanchuan, China",
"LUSAKA, Zambia",
"Qidong, China",
"Faridabad, India",
"Zaoyang, China",
"Zhucheng, China",
"Rostov-na-Donu, Russia",
"Jiangdu, China",
"Xiangcheng, China",
"Zigong, China",
"Jining (Shandong), China",
"Edmonton, Canada",
"Allahabad, India",
"Beiliu, China",
"Dnipropetrovsk, Ukraine",
"Gongzhuling, China",
"Qinzhou, China",
"Ufa, Russia",
"Sendai, Japan",
"Volgograd, Russia",
"Ezhou, China",
"GUATEMALA CITY, Guatemala",
"Zhongxiang, China",
"AMSTERDAM, Netherlands",
"BRUSSELS, Belgium",
"BAMAKO, Mali",
"Ziyang, China",
"ANTANANARIVO, Madagascar",
"Mudanjiang, China",
"Amritsar, India",
"Vijayawada, India",
"Haora (Howrah), India",
"Donetsk (Donestskaya oblast), Ukraine",
"Huazhou, China",
"Fuzhou (Jiangxi), China",
"Pimpri Chinchwad, India",
"DUBLIN, Ireland",
"Rajkot, India",
"Sao Luís, Brazil",
"Béni-Mellal, Morocco",
"Lianyuan, China",
"Liupanshui, China",
"Kaduna, Nigeria",
"Kitakyushu, Japan",
"Qianjiang, China",
"Perm, Russia",
"Odessa, Ukraine",
"Qom, Iran",
"Yongchuan, China",
"Peshawar, Pakistan",
"Linzhou, China",
"Benxi, China",
"ULAANBAATAR, Mongolia",
"Zhangqiu, China",
"Yongzhou, China",
"Sao Gonçalo, Brazil",
"Srinagar, India",
"Ghaziabad, India",
"Xinyi (Jiangsu), China",
"Köln, Germany",
"Zhangjiagang, China",
"Wafangdian, China",
"Xianyang, China",
"Liaocheng, China",
"Ahwaz, Iran",
"Taishan, China",
"Linhai, China",
"Feicheng, China",
"Suwon (Puwan), South Korea",
"Wuwei, China",
"Haimen, China",
"San Luis Potosí, Mexico",
"Liling, China",
"Xinhui, China",
"Gaziantep, Turkey",
"Krasnoyarsk, Russia",
"Chiba, Japan",
"Voronezh, Russia",
"Durg-Bhilai Nagar, India",
"Ruzhou, China",
"Maceió, Brazil",
"Yichun (Jiangxi), China",
"Al-Madinah, Saudi Arabia",
"Yulin (Guangxi), China",
"Seongnam, South Korea",
"Yueyang, China",
"Yiwu, China",
"San Jose (CA), United States",
"Jixi, China",
"MANAGUA, Nicaragua",
"Xinyi (Guangdong), China",
"Safi, Morocco",
"Guangyuan, China",
"Soweto, South Africa",
"Zhangjiakou, China",
"Baoding, China",
"Cartagena, Colombia",
"Huludao, China",
"Pingdingshan, China",
"Torino, Italy",
"Zengcheng, China","Laiyang, China","Qingzhou, China","Aurangabad, India","Lattakia, Syria","Mérida, Mexico","Laizhou, China","Thiruvananthapuram, India","Weinan, China","Wuchang, China","Guangshui, China","Gaizhou, China","Göteborg, Sweden","Xiaogan, China","Torreón, Mexico","Jiaxing, China","Kozhikode, India","Salé, Morocco","Zhuzhou, China","Tyneside, United Kingdom","Hengyang, China","Dehui, China","Honghu, China","Danyang, China","Daye, China","Solapur, India","Xingning, China","Xiangfan, China","Shubra-El-Khema, Egypt","Luoding, China","Gwalior, India","Ranchi, India","Huiyang, China","Mombasa, Kenya","Jinzhou (Liaoning), China","Jiangyan, China","Chenghai, China","Jiamusi, China","Songzi, China","TEGUCIGALPA, Honduras","Wujiang, China","Jodhpur, India","Duque de Caxias, Brazil","Xi'ning, China","Yuyao, China","Hezhou, China","Jiangyou, China","Tiruchchirappalli, India","Baoshan, China","Saratov, Russia","Nova Iguaçu, Brazil","Ankang, China","Gaomi, China","Yangchun, China","Santiago de los Caballeros, Dominican Republic","Danzhou, China","LA PAZ, Bolivia","Zhuanghe, China","Zhuhai, China","Zhaodong, China","Sakai, Japan","Haikou, China","Jiaonan, China","El Alto, Bolivia","Xuancheng, China","Wuchuan, China","Yuhang, China","Qinhuangdao, China","Bogor, Indonesia","Kermanshah, Iran","Longhai, China","Liverpool, United Kingdom","Yanshi, China","Guwahati, India","Yichun (Heilongjiang), China","Konya, Turkey","Barquisimeto, Venezuela","Yingde, China","Bengbu, China","Yibin, China","Chandigarh, India","Xiangxiang, China","Yinchuan, China","Valencia, Spain","Guilin, China","Hamamatsu, Japan","Sao Bernardo do Campo, Brazil","Deir El-Zor, Syria","BISHKEK, Kyrgyzstan","Teresina, Brazil","Suihua, China","BENGHAZI, Libya","Jiutai, China","Meishan, China","Zaporizhya, Ukraine","Gaoyou, China","Marseille, France","Kaifeng, China","Changning, China","Tongliao, China","Natal, Brazil","Bandar Lampung, Indonesia","Dongying, China","Gaoan, China","Langzhong, China","Lichuan, China","Hubli-Dharwad, India","Mysore, India","Niigata, Japan","Indianapolis (IN), United States","Jiaozhou, China","Pingxiang (Jiangxi), China","Haiphong, Viet Nam","Arequipa, Peru","Jacksonville (FL), United States","Tanger, Morocco","Dandong, China","KISHINEV, Moldova","Krasnodar, Russia","ZAGREB, Croatia","Xinmi, China","Chaohu, China","Xinyu, China","Gongyi, China","Huixian, China","Xinxiang, China","Port Elizabeth, South Africa","Mendoza, Argentina","Nantong, China","Pengzhou, China","Khulna, Bangladesh","Malang, Indonesia","Padang, Indonesia","Anyang, China","Renqiu, China","Foshan, China","Anshun, China","Chihuahua, Mexico","Campo Grande, Brazil","Lódz, Poland","Goyang, South Korea","Benin City, Nigeria","Bucheon (Puchon), South Korea","Gaocheng, China","Pulandian, China","Hejian, China","Dafeng, China","Kraków, Poland","Enshi, China","Dongyang, China","Lviv, Ukraine","Kunshan, China","Shuangcheng, China","Salem, India","Jiaozuo, China","Ad-Dammam, Saudi Arabia","Huaibei, China","Liyang, China","Samut Prakan, Thailand","Rongcheng, China","Cenxi, China","Nampho, North Korea","Columbus (OH), United States","Bareilly, India","Leping, China","Laixi, China","Liaoyang, China","Zhaotong, China","JERUSALEM, Israel","Tainan, China","Cuernavaca, Mexico","RIGA, Latvia","Linfen, China","Québec, Canada","Lingbao, China","Shangyu, China","Wuan, China","Hailun, China","Xingyi, China","Wuxue, China","Cebu, Philippines","Aguascalientes, Mexico","Tolyatti, Russia","Hamilton, Canada","Zhoushan, China","Langfang, China","Osasco, Brazil","Nonthaburi, Thailand","Dashiqiao, China","Tongxiang, China","Yichang, China","Yangzhou, China","Blantyre City, Malawi","Hamhung, North Korea","Jalandhar, India","Al-Rakka, Syria","NIAMEY, Niger","Xiangtan, China","Winnipeg, Canada","Oran (Wahran), Algeria","Kota, India","Sevilla, Spain","Navi Mumbai (New Bombay), India","Port Harcourt, Nigeria","Saltillo, Mexico","Khartoum North, Sudan","Shizuoka, Japan","Yuanjiang, China","Raipur, India","Kryviy Rig, Ukraine","Yingkou, China","Wuhu, China","Zhenjiang, China","Querétaro, Mexico","Nankang, China","Wugang (Hunan), China","Hegang, China","Linqing, China","PRETORIA, South Africa","Zunyi, China","Panzhihua, China","Austin (TX), United States","Changle, China","Lianyungang, China","Yancheng, China","Zunhua, China","Changyi, China","Meknès, Morocco","Qiongshan, China","Bulawayo, Zimbabwe","Wendeng, China","Okayama, Japan","Santo André, Brazil","RABAT, Morocco","Pakanbaru, Indonesia","Nehe, China","Memphis (TN), United States","Joao Pessoa, Brazil","KATHMANDU, Nepal","Longkou, China","Shengzhou, China","Antalya, Turkey","Kumamoto, Japan","LILONGWE, Malawi","Mexicali, Mexico","Kaiping, China","Palermo, Italy","Aligarh, India","Nottingham, United Kingdom","Haining, China","Mosul, Iraq","Hermosillo, Mexico","Tongcheng, China","Shulan, China","Miluo, China","Bhubaneswar, India","Yangquan, China","Chenzhou, China","Haiyang, China","Morelia, Mexico","Huangshi (Hubei), China","Xinmin, China","Tétouan, Morocco","Barnaul, Russia","Qixia, China","Jaboatao dos Guarapes, Brazil","Chongzhou, China","Cotonou, Benin","Yingcheng, China","Zaragoza, Spain","Changzhi, China","Qujing, China","Linghai, China","Changge, China","Trujillo, Peru","Tampico, Mexico","Maoming, China","Morón, Argentina","La Plata, Argentina","Ciudad Guayana, Venezuela","Moradabad, India","Jieshou, China","Sheffield, United Kingdom","Donggang, China","Jingjiang, China","Acheng, China","Acapulco (de Juárez), Mexico","Veracruz, Mexico","Ulyanovsk, Russia","Wroclaw, Poland","Jieyang, China","Shaoxing, China","Qian'an, China","Nanchuan, China","Qionglai, China","Deyang, China","Sagamihara, Japan","Fuyang (Anhui), China","Fuxin, China","Jiyuan, China","Puente Alto, Chile","Qufu, China","Gaoyao, China","Gorakhpur, India","Fort Worth (TX), United States","Xinji, China","San Miguel de Tucumán, Argentina","Dujiangyan, China","The Hague, Netherlands","Bhiwandi, India","Culiacán Rosales, Mexico","Lingyuan, China","Xingyang, China","Maiduguri, Nigeria","Genova, Italy","Meihekou, China","Izhevsk, Russia","Jeonju (Chonchu), South Korea","Leling, China","Xichang, China","COLOMBO, Sri Lanka","Zaria, Nigeria","Anlu, China","Sao José dos Campos, Brazil","Charlotte (NC), United States","Yizheng, China","Malmö, Sweden","Weihai, China","Xinzheng, China","Dengfeng, China","Vladivostok, Russia","Shaoyang, China","Taizhou (Jiangsu), China","Jammu, India","Lanxi, China","Yuncheng, China","Kagoshima, Japan","Yaroslave, Russia","Contagem, Brazil","Shishou, China","Panjin, China","Zamboanga, Philippines","Orumiyeh, Iran","Binzhou, China","Kisumu, Kenya","Baoji, China","Uberlândia, Brazil","El Paso (TX), United States","Yunzhou, China","Kénitra, Morocco","Diyarbakir, Turkey","Jurong, China","Cúcuta, Colombia","Zhaoyuan, China","Huizhou, China","Tianchang, China","Dortmund, Germany","Shihezi, China","Shiyan, China","Cuttack, India","Cochabamba, Bolivia","Cheongju, South Korea","Jingmen, China","Shangzhi, China","Anqing, China","Chongjin, North Korea","Stuttgart, Germany","Rushan, China","KINGSTON, Jamaica","Milwaukee (WI), United States","Sorocaba, Brazil","Glasgow, United Kingdom","Khabarovsk, Russia","Guanghan, China","Warangal, India","Irkutsk, Russia","Tyumen, Russia","Lomas de Zamora, Argentina","Beipiao, China","Funabashi, Japan","Mingguang, China","Düsseldorf, Germany","Shenzhou, China","Içel, Turkey","Zhangzhou, China","Xianning, China","Maanshan, China","Bandjarmasin, Indonesia","Callao, Peru","Poznan, Poland","Kayseri, Turkey","Chon Buri, Thailand","Quetta, Pakistan","Shuozhou, China","Samarinda, Indonesia","HELSINKI, Finland","Akesu, China","Novokuznetsk, Russia","Málaga, Spain","Fengcheng (Liaoning), China","Hachioji, Japan","Ribeirao Prêto, Brazil","Beihai, China","Jamnagar, India","NOUAKCHOTT, Mauritania","Bazhou, China","Yongkang, China","Louisville (KY), United States","Chizhou, China","Huaiyin, China","Fuan, China","Bhilai Nagar, India","Dezhou, China","Makhachkala, Russia","Xingping, China","Jiujiang, China","Bristol, United Kingdom","Botou, China","Fengnan, China","ASTANA, Kazakhstan","Yizhou, China","Amravati, India","Nashville-Davidson (TN), United States","Batam, Indonesia","Orenburg, Russia","Zhuozhou, China","Las Vegas (NV), United States","Cancun, Mexico","Longyan, China","OSLO, Norway","Cuiabá, Brazil","Tiruppur, India","VILNIUS, Lithuania","Bremen, Germany","Gold Coast-Tweed, Australia","Gaobeidian, China","Mangalore, India","Songyuan, China","Yangjiang, China","Wanyuan, China","Jiangmen, China","Xingtai, China","Shaoguan, China","Feira de Santana, Brazil","Guixi, China","Ruijin, China","Zahedan, Iran","Jinzhong, China","Portland (OR), United States","Jintan, China","Reynosa, Mexico","Ilorin, Nigeria","Oklahoma City (OK), United States","Nakhon Ratchasima, Thailand","N'DJAMENA, Chad","Shangzhou, China","Panshi, China","Kerman, Iran","Kaiyuan (Liaoning), China","ISLAMABAD, Pakistan","SARAJEVO, Bosnia and Herzegovina","Bikaner, India","DUSHANBE, Tajikistan","VIENTIANE, Laos","Dehradun, India","Zhangshu, China","Beining, China","ABU DHABI, United Arab Emirates","Shimkent, Kazakhstan","Xingcheng, China","Imbaba, Egypt","Yicheng, China","SKOPLJE, Macedonia","Kadhimain, Iraq","At-Ta'if, Saudi Arabia","Dali, China","Fuding, China","Jinzhou (Hebei), China","Renhuai, China","Mira-Bhayandar, India","Kemerovo, Russia","Duisburg, Germany","Rasht, Iran","San Pedro Sula, Honduras","Bucaramanga, Colombia","Bhavnagar, India","Conghua, China","Changwon, South Korea","Mianzhu, China","Pohang, South Korea","Tucson (AZ), United States","Taicang, China","Matsuyama, Japan","Hannover, Germany","Guntur, India","Lin'an, China","Higashiosaka, Japan","Wanning, China","Mar del Plata, Argentina","Ryazan, Russia","Quilmes, Argentina","Tomsk, Russia","Linhe, China","Chibi, China","Jos, Nigeria","Penza, Russia","Laohekou, China","Wenchang, China","Juiz de Fora, Brazil","Zhijiang, China","Newcastle, Australia","Pinghu, China","Zhaoqing, China","Naberezhnye Tchelny, Russia","Qingyuan, China","Tula, Russia","Belgaum, India","Pondicherry, India","Aracaju, Brazil","Pasig, Philippines","Mykolayiv (Nikolaevskaya oblast), Ukraine","Ibagué, Colombia","Hanzhong, China","Tlaxcala, Mexico","Chuxiong, China","Denpasar, Indonesia","Lipetsk, Russia","Dengta, China","Tuxtla Gutiérrez, Mexico","Songkhla, Thailand","Mariupol, Ukraine","Danjiangkou, China","Chiclayo, Peru","COPENHAGEN, Denmark","Penglai, China","Oaxaca de Juárez, Mexico","Aba, Nigeria","Astrakhan, Russia","MACAO, China : Macao SAR","Eskisehir, Turkey","Shishi, China","Kannur, India","Ananindeua, Brazil","Bokaro Steel City, India","SAN SALVADOR, El Salvador","Kolhapur, India","Xinzhou, China","Joinville, Brazil","Dangyang, China","Londrina, Brazil","Hebi, China","Ganzhou, China","Hamadan, Iran","Yucheng, China","Albuquerque (NM), United States","Agadir, Morocco","Chuzhou, China","Genève, Switzerland","Durgapur, India","Siping, China","Surakarta, Indonesia","Gomel, Belarus","Ajmer, India","Leipzig, Germany","Kirov, Russia","Belford Roxo, Brazil","Nanping, China","Luhansk, Ukraine","Al-Sharjah, United Arab Emirates","Shuangyashan, China","Qitaihe, China","Zhangye, China","Nürnberg, Germany","Bâle, Switzerland","Oujda, Morocco","Erbil, Iraq","Valenzuela, Philippines","Hongjiang, China","Baicheng, China","Raurkela, India","PANAMA CITY, Panama","Barcelona-Puerto La Cruz, Venezuela","Huanghua, China","Pontianak, Indonesia","Himeji, Japan","Sanya, China","Orizaba, Mexico","Dunhua, China","Kawaguchi, Japan","Durango (Victoria de Durango), Mexico","Jian'ou, China","Tombouctou, Mali","Niterói, Brazil","Dresden, Germany","Arak, Iran","Soledad, Colombia","Chaoyang (Liaoning), China","Shahe, China","Jiaohe, China","Long Beach (CA), United States","Jiangshan, China","Jian (Jiangxi), China","Anda, China","Jiande, China","Ulhasnagar, India","Las Piñas, Philippines","Matsudo, Japan","Port Said, Egypt","Yuanping, China","Gaoping, China","Fenghua, China","Makati, Philippines","Qingzhen, China","Siliguri, India","Kurashiki, Japan","Ipoh, Malaysia","Lanus, Argentina","Taguig, Philippines","Nan'gong, China","Al-Kamishli, Syria","Sao Joao de Meriti, Brazil","Ichikawa, Japan","London, Canada","Nishinomiya, Japan","Constantine (Qacentina), Algeria","Enping, China","Weihui, China","Adhamiyah, Iraq","Kitchener, Canada","Duyun, China","Jhansi, India","Amagasaki, Japan","Oita, Japan","Liaoyuan, China","Cagayan de Oro, Philippines","Antwerpen (Anvers), Belgium","Brighton/Worthing/Littlehampton, United Kingdom","Fresno (CA), United States","Baiyin, China","Tonghua, China","Maracay, Venezuela","Sargodha, Pakistan","Utsunomiya, Japan","Gdansk, Poland","Sanhe, China","Sacramento (CA), United States","Pingliang, China","New Orleans (LA), United States","Kanazawa, Japan","Zhangjiajie, China","Cheboksary, Russia","Gejiu, China","Aparecida de Goiania, Brazil","Saharanpur, India","Cleveland (OH), United States","Mixco, Guatemala","BANGUI, Central African Republic","Yulin (Shaanxi), China","LOME, Togo","Qionghai, China","Paranaque, Philippines","Edinburgh, United Kingdom","Linxiang, China","Puyang, China","Sangli-Miraj-Kupwad, India","Qinyang, China","Pereira, Colombia","Karaganda, Kazakhstan","Kansas City (MO), United States","Lyon, France","Jingdezhen, China","Jambi, Indonesia","Huadian, China","Putian, China","Jinghong, China","Cangzhou, China","Mesa (AZ), United States","Nagasaki, Japan","Beian, China","Portsmouth, United Kingdom","Bhatpara, India","Johore Bharu, Malaysia","Tabuk, Saudi Arabia","Leicester, United Kingdom","Taonan, China","Sanshui, China","Xinle, China","Virginia Beach (VA), United States","Mishan, China","Ning'an, China","Chengde, China","Bryansk, Russia","Hailin, China","Gulbarga, India","Bobo Dioulasso, Burkina Faso","Masan, South Korea","Tieling, China","Kaili, China","Ogbomosho, Nigeria","Shifang, China","Yanji, China","Yazd, Iran","Firozabad, India","Tirunelveli, India","Zarqa, Jordan","Matamoros, Mexico","Ujjain, India","Nanded, India","Daan, China","Campos dos Goytacazes, Brazil","Balikpapan, Indonesia","Bacolod, Philippines","Wuhai, China","SAN JUAN, Puerto Rico","Yokosuka, Japan","Santiago de Cuba, Cuba","BRATISLAVA, Slovakia","Jinhua, China","Matola, Mozambique","Lechang, China","Coatzacoalcos, Mexico","Emeishan, China","Kaliningrad (Kaliningradskaya oblast), Russia","Hengshui, China","Fangchenggang, China","Santa Marta, Colombia","Sialkote, Pakistan","Yongji, China","Toyama, Japan","DOHA, Qatar","Fujin, China","Kirkuk, Iraq","LIBREVILLE, Gabon","Fukuyama, Japan","Santos, Brazil","Cheonan, South Korea","Suez, Egypt","Murcia, Spain","Utrecht, Netherlands","Makyivka, Ukraine","Sao José do Rio Prêto, Brazil","Omaha (NE), United States","Xiaoyi, China","Mauá, Brazil","Soacha, Colombia","Malatya, Turkey","Manado, Indonesia","Toyota, Japan","Caxias do Sul, Brazil","Magnitogorsk, Russia","General Santos, Philippines","Sanliurfa, Turkey","Ivanovo, Russia","Szczecin, Poland","Sihui, China","Gaza, Palestine, Occupied Territory","Shanwei, China","Lianzhou, China","Malegaon, India","Zhalantun, China","Yuxi, China","Bahawalpur, Pakistan","Rajahmundry, India","Enugu, Nigeria","Betim, Brazil","ASHGABAT, Turkmenistan","General San Martín, Argentina","Florianópolis, Brazil","Santa Fé, Argentina","Basra, Iraq","Huangshan, China","Yakeshi, China","Heshan (Guangdong), China","Kursk, Russia","Tver, Russia","Machida, Japan","Pietermaritzburg, South Africa","Vila Velha, Brazil","Nellore, India","Shuangliao, China","Tongchuan, China","Hirakata, Japan","Yan'an, China","Ningde, China","Sochi, Russia","Huambo, Angola","Akola, India","Gifu, Japan","Ruichang, China","Loudi, China","Adan, Yemen","Luquan, China","Beira, Mozambique","St. Catharines, Canada","TALLINN, Estonia","Erzurum, Turkey","Fujisawa, Japan","Diadema, Brazil","Oakland (CA), United States","El-Mahalla El-Kubra, Egypt","Gao, Mali","Serra, Brazil","Gaya, India","TIRANA, Albania","Bochum, Germany","Yogyakarta, Indonesia","South Dum Dum, India","Namangan, Uzbekistan","Marikina, Philippines","Erode, India","Ardabil, Iran","Villa Nueva, Guatemala","Villavicencio, Colombia","Toulouse, France","Carapicuíba, Brazil","Udaipur, India","Maheshtala, India","Rajshahi, Bangladesh","Hami, China","Pasto, Colombia","Vellore, India","Olinda, Brazil","Changji, China","Fenyang, China","Hancheng, China","Toyonaka, Japan","Yidu, China","Thessaloniki, Greece","Montería, Colombia","Dazhou, China","Bournemouth, United Kingdom","Keelung, China","DJIBOUTI, Djibouti","Da Nang, Viet Nam","Tulsa (OK), United States","Halifax, Canada","Kuerle, China","Ningguo, China","Manizales, Colombia","Wuzhou, China","Porto Velho, Brazil","Kashiwa, Japan","Bello, Colombia","Kollam, India","Campina Grande, Brazil","Vereeniging, South Africa","Chiang Mai, Thailand","Muntinlupa, Philippines","An'guo, China","ABUJA, Nigeria","Nizhny Tagil, Russia","Villahermosa, Mexico","Nagano, Japan","Buraydah, Saudi Arabia","Samsun, Turkey","Honolulu (HI), United States","Las Palmas de Gran Canaria, Spain","PalmasdeGranCanaria, Spain","Sevastopol, Ukraine","WELLINGTON, New Zealand","Wakayama, Japan","Ulan-Ude, Russia","Palma de Mallorca, Spain","Christchurch, New Zealand","Jizhou, China","Huanggang, China","Xuchang, China","Bologna, Italy","Jiexiu, China","Tanta, Egypt","Nanxiong, China","Khamis Mushayt, Saudi Arabia","Toyohashi, Japan","Moji das Cruzes, Brazil","Ichinomiya, Japan","Ndola, Zambia","Salta, Argentina","Nara, Japan","Oyo, Nigeria","Colorado Springs (CO), United States","Reading/Wokingham, United Kingdom","Mansûra, Egypt","Wuppertal, Germany","Kakinada, India","Jalgaon, India","Hejin, China","Mogilev, Belarus","Klang, Malaysia","Macapá, Brazil","Brno, Czech Republic","Piracicaba, Brazil","Firenze, Italy","Iloilo, Philippines","Benoni, South Africa","Udon Thani, Thailand","Teesside, United Kingdom","Bydgoszcz, Poland","Valledupar, Colombia","Sulamaniya, Iraq","Davangere, India","Chaozhou, China","Warri, Nigeria","Arlington (TX), United States","Tongling, China","Kitwe, Zambia","The Potteries, United Kingdom","Bouake, Côte d'Ivoire","Piura, Peru","BEIRUT, Lebanon","Samarkand, Uzbekistan","Cariacica, Brazil","Misurata, Libya","Kaunas, Lithuania","Stavropol, Russia","Hsinchu, China","Vinnytsya, Ukraine","Dongfang, China","ASMARA, Eritrea","Simpheropol, Ukraine","Yi'ning, China","Bauru, Brazil","Iquitos, Peru","Nuevo Laredo, Mexico","Wuzhong, China","Uijeongbu (Eujeongbu), South Korea","Arkhangelsk, Russia","Asahikawa, Japan","Pasay, Philippines","Kahramanmaras, Turkey","Wichita (KS), United States","Okazaki, Japan","Tieli, China","Iwaki, Japan","Meizhou, China","Lublin, Poland","Bilbao, Spain","Panipat, India","Suita, Japan","Kherson, Ukraine","Itaquaquecetuba, Brazil","Abeokuta, Nigeria","San Juan, Argentina","Annaba, Algeria","Huaying, China","Vitebsk, Belarus","Takatsuki, Japan","Zixing, China","Petaling Jaya, Malaysia","Bloemfontein, South Africa","Onitsha, Nigeria","Bhagalpur, India","Fife, United Kingdom","Al-Rayyan, Qatar","Montes Claros, Brazil","Jundiaí, Brazil","Panihati, India","Lishui, China","Ahmednagar, India","Manukau, New Zealand","Irapuato, Mexico","Huaihua, China","Pelotas, Brazil","Jiuquan, China","Zanjan, Iran","Belgorod, Russia","Kathlehong, South Africa","SAN JOSE, Costa Rica","Kempton Park, South Africa","Oshawa, Canada","Avellaneda, Argentina","BERNE, Switzerland","Assyût, Egypt","Nice, France","Plovdiv, Bulgaria","Kaluga, Russia","Antofagasta, Chile","Mataram, Indonesia","Gumi (Kumi), South Korea","Raleigh (NC), United States","Dhule, India","Kashi (Xinjiang), China","Baise, China","Santa Ana (CA), United States","Vladimir, Russia","Jinju (Chinju), South Korea","Umlazi, South Africa","Lengshuijiang, China","Malabon, Philippines","Koriyama, Japan","Wudalianchi, China","Andizhan, Uzbekistan","Zhumadian, China","Takamatsu, Japan","Luxi (Yunnan), China","Sanming, China","Coventry/Bedworth, United Kingdom","Rajpur Sonarpur, India","Carrefour, Haiti","Tokorozawa, Japan","Taraz, Kazakhstan","Khouribga, Morocco","Buenaventura, Colombia","Sukkur, Pakistan","Surat Thani, Thailand","Baishan, China","Yong'an, China","Yaan, China","Kaesong, North Korea","Victoria, Canada","Gwangmyeong (Kwangmyong), South Korea","Kawagoe, Japan","Ciudad del Este, Paraguay","Kochi, Japan","Canoas, Brazil","Akita, Japan","Basilan, Philippines","Windsor, Canada","Gimhae (Kimhae), South Korea","Anaheim (CA), United States","San Miguelito, Panama","Muzaffarnagar, India","Vladikavkaz (Osetinskaya ASSR), Russia","Bilaspur, India","Thrissur, India","Sokoto, Nigeria","Sao Vicente, Brazil","Chimbote, Peru","Kurgan, Russia","Franca, Brazil","Al-Ayn, United Arab Emirates","Sanandaj, Iran","Cardiff, United Kingdom","Shangrao, China","Khon Kaen, Thailand","Cuzco, Peru","Sinuiji, North Korea","Bari, Italy","CANBERRA, Australia","Orel, Russia","Maringá, Brazil","Van, Turkey","Zhoukou, China","Iksan (Iri), South Korea","Saransk, Russia","Patiala, India","Shahjahanpur, India","Ribeirao das Neves, Brazil","Córdoba, Spain","Alicante, Spain","Eindhoven, Netherlands","Pachuca (de Soto), Mexico","Bielefeld, Germany","North Lanarkshire, United Kingdom","Celaya, Mexico","Kurnool, India","Grodno, Belarus","Valladolid, Spain","Birkenhead, United Kingdom","Neiva, Colombia","Murmansk, Russia","Mathura, India","Anápolis, Brazil","Volzhsky, Russia","Maebashi, Japan","Hechi, China","Jianyang (Fujian), China","Smolensk, Russia","Xifeng, China","Ta'izz, Yemen","Vitória, Brazil","Bellary, India","Pittsburgh (PA), United States","Iasi, Romania","Koshigaya, Japan","Korba, India","Bandar-e-Abbas, Iran","Kamarhati, India","Shizuishan, China","Khayelitsa, South Africa","NoviSad, Serbia","Rio Branco, Brazil","Meixian, China","Caucaia, Brazil","Khoramabad, Iran","Wugang (Henan), China","Okene, Nigeria","Pathum Thani, Thailand","Naha, Japan","Varna, Bulgaria","Hulin, China","Aomori, Japan","Calabar, Nigeria","Ostrava, Czech Republic","Petrópolis, Brazil","Miyazaki, Japan","Muling, China","Lausanne, Switzerland","Sagar, India","Foz do Iguaçu, Brazil","Najaf, Iraq","Cincinnati (OH), United States","Tongren, China","Port Sudan, Sudan","Cherepovets, Russia","Mannheim, Germany","Qazvin, Iran","Huancayo, Peru","Camagüey, Cuba","Yamunanagar, India","Kurume, Japan","Chita, Russia","Cluj-Napoca, Romania","Constanta, Romania","Muzaffarpur, India","Guarujá, Brazil","Ponta Grossa, Brazil","Pavlodar, Kazakhstan","Southampton, United Kingdom","Jincheng, China","Luohe, China","Cuenca, Ecuador","Yokkaichi, Japan","Ganja, Azerbaijan","Timisoara, Romania","Tepic, Mexico","Nampula, Mozambique","Yeosu, South Korea","Poltava, Ukraine","Catania, Italy","Tirupati, India","Ambattur, India","Brest, Belarus","South Lanarkshire, United Kingdom","Otsu, Japan","Yangzhong, China","Barcelona, Venezuela","Kingston-upon-Hull, United Kingdom","Toledo (OH), United States","Gaoming, China","Craiova, Romania","Wonsan, North Korea","Latur, India","Paulista, Brazil","San Isidro, Argentina","Blumenou, Brazil","Horlivka, Ukraine","Al-Hudaydah (Hodeidah), Yemen","Dexing, China","Chandrapur, India","Aurora (CO), United States","Kerbala, Iraq","Galati, Romania","Naltchik, Russia","Kharagpur, India","Kasugai, Japan","Bakersfield (CA), United States","Denizli, Turkey","Bialystok, Poland","Anning, China","NEW DELHI, India","Chernihiv, Ukraine","Rohtak, India","Vologda, Russia","Jishou, China","Århus, Denmark","Hakodate, Japan","Noida, India","Jhang, Pakistan","Vigo, Spain","Garoua, Cameroon","Fuquan, China","Resistencia, Argentina","Viña del Mar, Chile","Kaiyuan (Yunnan), China","Sumgayit, Azerbaijan","Cherkasy, Ukraine","Akashi, Japan","Fukushima, Japan","Shimonoseki, Japan","Kukatpalle, India","Soyapango, El Salvador","Surgut, Russia","Riverside (CA), United States","Kulti, India","Vitória da Conquista, Brazil","Brahmapur, India","Vicente López, Argentina","Sanmenxia, China","Ust-Kamenogorsk, Kazakhstan","Shaowu, China","Al-Hufuf, Saudi Arabia","Kindia, Guinea","Morioka, Japan","Nizamabad, India","Stockton (CA), United States","Palmira, Colombia","Quzhou, China","Barddhaman, India","Ichalakaranji, India","Kuitun, China","Uberaba, Brazil","Al-Mubarraz, Saudi Arabia","Iligan, Philippines","Sumy, Ukraine","Cascavel, Brazil","Delmas, Haiti","Sakarya, Turkey","Corpus Christi (TX), United States","Caruaru, Brazil","Tambov, Russia","Tongi, Bangladesh","Gebze, Turkey","Nzérékoré, Guinea","Alappuzha, India","Armenia, Colombia","Ciudad Victoria, Mexico","GABORONE, Botswana","Buonmathuot, Viet Nam","Gelsenkirchen, Germany","Semipalatinsk, Kazakhstan","Elazig, Turkey","Rampur, India","Novorossiysk, Russia","Brasov, Romania","Newark (NJ), United States","Susano, Brazil","Sheikhu Pura, Pakistan","Ichihara, Japan","Bhilwara, India","Zuwarah, Libya","GEORGETOWN, Guyana","Jeju (Cheju), South Korea","Buffalo (NY), United States","Limeira, Brazil","Roodepoort, South Africa","Ciudad Bolívar, Venezuela","Mandaluyong, Philippines","Abadan, Iran","Kuching, Malaysia","Batman, Turkey","Karlsruhe, Germany","Zhytomyr, Ukraine","Belfast, United Kingdom","Santarém, Brazil","San Bernardo, Chile","Gyeongju (Kyongju), South Korea","Yoshkar-ola, Russia","St. Paul (MN), United States","Valparaíso, Chile","Anchorage (AK), United States","Huozhou, China","Wollongong, Australia","Holguín, Cuba","Gijón, Spain","Shimoga, India","Kostroma, Russia","Islam Shahr (Qasemabad), Iran","Yao, Japan","Cirebon, Indonesia","Phyongsong, North Korea","Gunsan (Kunsan), South Korea","Jining (Inner Mongolia), China","Mérida, Venezuela","Komsomolsk-na-Amure, Russia","San Cristóbal, Venezuela","Pekalongan, Indonesia","Rajarhat Gopalpur, India","Taubaté, Brazil","Gravatai, Brazil","Swansea, United Kingdom","Nantes, France","Larkana, Pakistan","Kelamayi, China","Santa Maria, Brazil","Sukabumi, Indonesia","Banda Aceh, Indonesia","Nakhon Si Thammarat, Thailand","Southend, United Kingdom","Venezia, Italy","Wulanhaote, China","Irbid, Jordan","Hilla, Iraq","Wiesbaden, Germany","Wonju, South Korea","Lexington-Fayette (KY), United States","Ibaraki, Japan","Shillong, India","Tokushima, Japan","Angeles, Philippines","Monclova, Mexico","Zagazig, Egypt","Butuan, Philippines","Kakogawa, Japan","Ha'il, Saudi Arabia","Darbhanga, India","Haifa, Israel","San Pedro de Macoris, Dominican Republic","Taganrog, Russia","Nasariya, Iraq","Suncheon, South Korea","Sterlitamak, Russia","Alwar, India","Petrozavodsk, Russia","Cumaná, Venezuela","Barueri, Brazil","Zhangping, China","Münster (Westf.), Germany","Chiayi, China","Fengzhen, China","Gunpo (Kunpo), South Korea","Mönchengladbach, Germany","Strasbourg, France","Dasarahalli, India","Santiago del Estero, Argentina","Yakutsk, Russia","Chemnitz, Germany","Boksburg, South Africa","Hisar, India","Mito, Japan","Tarlac, Philippines","Hailaer, China","Maturín, Venezuela","L.B. Nagar, India","Viamao, Brazil","Yunfu, China","Bally, India","Santa Ana, El Salvador","Longjing, China","Kankan, Guinea","Sao José dos Pinhais, Brazil","Blackpool, United Kingdom","Cuddapah, India","Faiyûm, Egypt","Bahía Blanca, Argentina","Verona, Italy","Petrolina, Brazil","Dzerzhinsk (Novgorodskaya oblast), Russia","Ratchaburi, Thailand","Mandaue, Philippines","Popayán, Colombia","Governador Valadares, Brazil","Katsina, Nigeria","San Miguel, El Salvador","Parbhani, India","Hiratsuka, Japan","Gajuwaka, India","Nôvo Hamburgo, Brazil","Volta Redonda, Brazil","Corrientes, Argentina","Aktobe, Kazakhstan","Sivas, Turkey","Floridablanca, Colombia","Thiès, Senegal","Yamagata, Japan","Dnieprodzerzhynsk, Ukraine","Ismailia, Egypt","Augsburg, Germany","Várzea Grande, Brazil","Bengkulu, Indonesia","Halle, Germany","NIS, Serbia","PORT MORESBY, Papua New Guinea","Sariwon, North Korea","Ubon Ratchathani, Thailand","Bratsk, Russia","Bijapur, India","Kirovohrad, Ukraine","Khmelnytskiy (Hmilnyk), Ukraine","Sari, Iran","Dongsheng, China","Chuncheon, South Korea","Gdynia, Poland","Baguio, Philippines","Fukui, Japan","Junagadh, India","Kediri, Indonesia","Bamenda, Cameroon","Gujrat, Pakistan","Chishui, China","Tulufan, China","Orsk, Russia","Kure, Japan","Oshogbo, Nigeria","Baranagar, India","Mokpo, South Korea","Longquan, China","Plano (TX), United States","Osh, Kyrgyzstan","Lingwu, China","Leiden, Netherlands","Boa Vista, Brazil","Labé, Guinea","Alajuela, Costa Rica","St. Petersburg (FL), United States","Phra Nakhon Si Ayutthaya, Thailand","Pucallpa, Peru","Sfax, Tunisia","Qingtongxia, China","Tumkur, India","Russiefa, Jordan","Hospitalet de Llobregat, Spain","LJUBLJANA, Slovenia","Sasebo, Japan","Batangas, Philippines","Temuco, Chile","SUCRE, Bolivia","Najran (Aba as-Suud), Saudi Arabia","Shakhty, Russia","Batna, Algeria","Braunschweig, Germany","Saraburi, Thailand","Czestochowa, Poland","Imphal, India","Mardan, Pakistan","Embu, Brazil","Messina, Italy","Fuchu, Japan","Dordrecht, Netherlands","Praia Grande, Brazil","Kasur, Pakistan","Takasaki, Japan","Angarsk, Russia","Kashan, Iran","Hachinohe, Japan","Suqian, China","Syktivkar, Russia","Graz, Austria","Majnoon, Iraq","Rivne, Ukraine","Borujerd, Iran","Aachen, Germany","Plymouth, United Kingdom","Bergen, Norway","Anantapur, India","Aldershot, United Kingdom","Coruña(A), Spain","La Coruña, Spain","Jinshi, China","PARAMARIBO, Suriname","Thoothukkudi (Tuticorin), India","Farrukhabad-cum-Fategarh, India","Huayin, China","Tegal, Indonesia","Neyagawa, Japan","Krefeld, Germany","Dezful, Iran","Sincelejo, Colombia","Nizhenvartovsk, Russia","Narayanganj, Bangladesh","Chiang Rai, Thailand","Rangpur, Bangladesh","Gorgan, Iran","Juàzeiro do Norte, Brazil","Jian (Jilin), China","Tiefa, China","Jersey City (NJ), United States","Glendale (AZ), United States","Lincoln (NE), United States","Habra, India","Akure, Nigeria","Itagüi, Colombia","Kasukabe, Japan","Chernivtsy, Ukraine","Granada, Spain","Sumaré, Brazil","Tembisa, South Africa","Bukhara, Uzbekistan","Dire Dawa, Ethiopia","Magé, Brazil","Derby, United Kingdom","Ramagundam, India","Fuji, Japan","Qods, Iran","Ipatinga, Brazil","Nagaoka, Japan","Luton/Dunstable, United Kingdom","Soka, Japan","Lishi, China","Karradah Sharqiyah, Iraq","Jalna, India","Saskatoon, Canada","BUJUMBURA, Burundi","Zacatecas, Mexico","Nakhon Pathom, Thailand","Magdeburg, Germany","Chandler (AZ), United States","Kosice, Slovakia","Kassala, Sudan","Kota Bahru, Malaysia","Engels, Russia","Kiel, Germany","KIGALI, Rwanda","Rahimyar Khan, Pakistan","WINDHOEK, Namibia","Ratlam, India","Espoo, Finland","Kousséri, Cameroon","Gent (Gand), Belgium","PORTO-NOVO, Benin","Imperatriz, Brazil","Henderson (NV), United States","Ivano-Frankivsk, Ukraine","Hafar al-Batin, Saudi Arabia","Bihar, India","Greensboro (NC), United States","Norfolk (VA), United States","The Medway Towns, United Kingdom","Ploiesti, Romania","Barasat, India","Birmingham (AL), United States","Durg, India","Avadi, India","Simao, China","Dewas, India","Porto, Portugal","Navotas, Philippines","Manisa, Turkey","Kremenchuh, Ukraine","Tacna, Peru","Uralsk, Kazakhstan","Blida (El Boulaïda), Algeria","Mossoró, Brazil","Aizawl, India","Al-Obeid, Sudan","Navsari, India","Satna, India","Gurgaon, India","Haeju, North Korea","Chigasaki, Japan","Gangneung (Kangnung), South Korea","Gyeongsan, South Korea","Kuala Terengganu, Malaysia","Trabzon, Turkey","Kaolack, Senegal","Heyuan, China","Acarigua-Araure, Venezuela","Matsumoto, Japan","Vitoria-Gasteiz, Spain","Balikesir, Turkey","Mymensingh, Bangladesh","Colimas, Mexico","Nyala, Sudan","Sambalpur, India","Aberdeenshire, United Kingdom","Rancagua, Chile","Nizhnekamsk, Russia","Binjai, Indonesia","Radom, Poland","Scottsdale (AZ), United States","Quthbullapur, India","Montpellier, France","Biisk, Russia","Kandahar (Quandahar), Afghanistan","Maroua, Cameroon","Taboao da Serra, Brazil","Sosnowiec, Poland","Sonipat, India","Houma, China","Bole, China","LEFKOSIA, Cyprus","Pematang Siantar, Indonesia","English Bazar, India","Ambon, Indonesia","Marília, Brazil","AsSeeb, Oman","Kanggye, North Korea","Fort Wayne (IN), United States","Santa Cruz de Tenerife, Spain","Mwanza, Tanzania","Lasa, China","Mohammedia, Morocco","Cabanatuan, Philippines","Ganganagar, India","Tarsus, Turkey","Al-Jubayl, Saudi Arabia","Tilburg, Netherlands","Atsugi, Japan","Oberhausen, Germany","Baton Rouge (LA), United States","Karnal, India","San Fernando City, Philippines","Barinas, Venezuela","Madison (WI), United States","Bayamón, Puerto Rico","Badalona, Spain","Nhatrang, Viet Nam","Yamato, Japan","Itaboraí, Brazil","Ilhéus, Brazil","Palmas, Brazil","Rishon Leziyyon, Israel","Hialeah (FL), United States","Hardwar, India","Ageo, Japan","Groznyi, Russia","North Dumdum, India","Concepción, Chile","Takarazuka, Japan","Wadhwan, India","Santa Luzia (Minas Gerais), Brazil","George Town, Malaysia","Aswan, Egypt","Ternopil, Ukraine","Hué, Viet Nam","Elche, Spain","Chesapeake (VA), United States","Bobruisk, Belarus","Sao Carlo, Brazil","Starsy Oskol, Russia","Lipa, Philippines","Anand, India","Chungju, South Korea","Ozhukarai, India","Bathinda, India","Machala, Ecuador","Velikiy Novgorod, Russia","Lapu-Lapu, Philippines","Lampang, Thailand","Prokopyevsk, Russia","Northshore, New Zealand","Braila, Romania","Oruro, Bolivia","Campeche, Mexico","Garland (TX), United States","Chofu, Japan","Blagoveshchensk (Amurskaya oblast), Russia","Karimnagar, India","Thanjavur, India","Cantho, Viet Nam","Naihati, India","Eluru, India","Sabzewar, Iran","Bordeaux, France","Helong, China","Sete Lagoas, Brazil","Sunshine Coast, Australia","Alvorada, Brazil","Oviedo, Spain","Sétif (Stif), Algeria","Rybinsk, Russia","Lucheng, China","Lübeck, Germany","Ota, Japan","Cabimas, Venezuela","Orlando (FL), United States","Kalasin, Thailand","Sao Leopoldo, Brazil","Norilsk, Russia","Wuyishan, China","Aberdeen, United Kingdom","Nukus, Uzbekistan","Hapur, India","Paraná, Argentina","Tiruvottiyur, India","Santo Domingo de los Colorados, Ecuador","Jacareí, Brazil","Etawah, India","Al-Gezira, Sudan","Hunchun, China","Rochester (NY), United States","NASSAU, Bahamas","Akron (OH), United States","Posadas, Argentina","Padova, Italy","Chula Vista (CA), United States","Maunath Bhanjan, India","Lubbock (TX), United States","Heerlen-Kerkrade, Netherlands","Damanhûr, Egypt","Campha, Viet Nam","Highland, United Kingdom","Kramatorsk, Ukraine","Armavir, Russia","Amara, Iraq","Sahiwal, Pakistan","Laredo (TX), United States","Santa Clara, Cuba","Cartagena, Spain","Guantánamo, Cuba","Juliaca, Peru","Juazeiro, Brazil","Faizabad, India","Nagercoil, India","Kirikkale, Turkey","Joetsu, Japan","Numazu, Japan","Divinópolis, Brazil","San Pablo, Philippines","Kustanai, Kazakhstan","Dearne Valley, United Kingdom","Kielce, Poland","Torun, Poland","Modesto (CA), United States","Saga, Japan","Presidente Prudente, Brazil","Buri Ram, Thailand","Bauchi, Nigeria","Móstoles, Spain","Rennes, France","Kimberley, South Africa","Oradea, Romania","Neyshabur, Iran","Ica, Peru","Trieste, Italy","Gujiao, China","Raichur, India","Bafoussam, Cameroon","Pyatigorsk, Russia","Tampere, Finland","Mirzapur-cum-Vindhyachal, India","Hagen, Germany","Bharatpur, India","Itabuna, Brazil","Ajman, United Arab Emirates","Jinchang, China","Durham (NC), United States","Karshi, Uzbekistan","Najafabad, Iran","Secunderabad, India","Debrecen, Hungary","Talca, Chile","Adiyaman, Turkey","Americana, Brazil","DODOMA, Tanzania","Ambarnath, India","Reno (NV), United States","Greater Hobart, Australia","Toamasina, Madagascar","Turmero, Venezuela","Arrah, India","Rostock, Germany","San Lorenzo, Paraguay","Itapevi, Brazil","Linxia, China","Freiburg im Breisgau, Germany","Isesaki, Japan","Kuantan, Malaysia","Arapiraca, Brazil","Ashdod, Israel","Tamale, Ghana","Uluberia, India","Abha, Saudi Arabia","Okara, Pakistan","Hortolandia, Brazil","Tottori, Japan","Menia, Egypt","Alcalá de Henares, Spain","Charleroi, Belgium","Erfurt, Germany","Bommanahalli, India","Rayong, Thailand","Sao José, Brazil","Kishiwada, Japan","Al-Kharj, Saudi Arabia","Mejicanos, El Salvador","Bila Tserkva (Belaya Tserkov), Ukraine","Maraba, Brazil","Sabadell, Spain","Tsukuba, Japan","Fremont (CA), United States","Probolinggo, Indonesia","Balakovo, Russia","Atushi, China","Taiping, Malaysia","Montgomery (AL), United States","Glendale (CA), United States","Al Khums, Libya","Ziguinchor, Senegal","Groningen, Netherlands","Lutsk, Ukraine","Terrassa, Spain","Araraquara, Brazil","Jérez de la Frontera, Spain","Hitachi, Japan","Luzern, Switzerland","Gliwice, Poland","Nakhon Sawan, Thailand","2295","Shreveport (LA), United States","Odawara, Japan","San Bernardino (CA), United States","Regina, Canada","Cachoeiro de Itapemirim, Brazil","Serampore, India","Samut Sakhon, Thailand","BISSAU, Guinea-Bissau","Kokand, Uzbekistan","Porbandar, India","Sirjan, Iran","Palakkad, India","Northampton, United Kingdom","Salmiya, Kuwait","Camacari, Brazil","Rio Grande, Brazil","Taranto, Italy","Spokane (WA), United States","Khammam, India","Purnia, India","Nadiad, India","Dindigul, India","Matsue, Japan","Babol, Iran","Diwaniya, Iraq","Yonkers (NY), United States","Maracanau, Brazil","Kassel, Germany","Severodvinsk, Russia","Lucena City, Philippines","Dehiwala-Mount Lavinia, Sri Lanka","Banja Luka, Bosnia and Herzegovina","Arlington (VA), United States","Pskov, Russia","Tacoma (WA), United States","Gandhinagar, India","Pamplona, Spain","Amol, Iran","Vizianagarm, India","Waitakere, New Zealand","Petropavlovsk-Kamchatsky, Russia","Portoviejo, Ecuador","Norwich, United Kingdom","Huntington Beach (CA), United States","Burhanpur, India","Olongapo, Philippines","Kofu, Japan","Des Moines (IA), United States","Kocaeli, Turkey","Grand Rapids (MI), United States","Richmond (VA), United States","Winston-Salem (NC), United States","Fuenlabrada, Spain","Irving (TX), United States","Seremban, Malaysia","Manta, Ecuador","Boise City (ID), United States","Suzuka, Japan","Jayapura, Indonesia","Barisal, Bangladesh","Heihe, China","Apopa, El Salvador","Ramadi, Iraq","Zlatoust, Russia","Itami, Japan","La Paz, Mexico","Yangsan, South Korea","Ath-Thuqbah, Saudi Arabia","Hamilton, New Zealand","Yamaguchi, Japan","Mobile (AL), United States","Al-Gadarif, Sudan","Kumagaya, Japan","Katihar, India","Le Havre, France","Augusta-Richmond (GA), United States","Zabrze, Poland","Brescia, Italy","Barrancabermeja, Colombia","Dera Ghazi Khan, Pakistan","Rio Claro, Brazil","Wusu, China","Petropavlovsk (Severo- Kazakhstanskaya oblast), Kazakhstan","REYKJAVIK, Iceland","Tuluá, Colombia","Nishitokyo, Japan","Mirpur Khas, Pakistan","Haarlem, Netherlands","Uji, Japan","Nazareth, Ethiopia","Agartala, India","Nawabshah, Pakistan","Osmaniye, Turkey","Minna, Nigeria","Bourgas, Bulgaria","Yumen, China","Split, Croatia","Vantaa, Finland","Yanbu al-Bahr, Saudi Arabia","Santa Bárbara D'Oeste, Brazil","Linz, Austria","Kancheepuram, India","Passo Fundo, Brazil","Criciúma, Brazil","Dunhuang, China","Carolina, Puerto Rico","Pali, India","Bhusawal, India","Tanga, Tanzania","Krishnarajapura, India","Munger, India","Luziânia, Brazil","Bytom, Poland","Reims, France","Varamin, Iran","Liège (Luik), Belgium","Birjand, Iran","Ife, Nigeria","Irvine (CA), United States","Murwara (Katni), India","Klaipeda, Lithuania","Odense, Denmark","Dourados, Brazil","Cork, Ireland","Hetian, China","Singrauli, India","Mesquita, Brazil","Sikar, India","Almería, Spain","Columbus (GA), United States","Be'er Sheva, Israel","Nong Khai, Thailand","Linjiang, China","Prato, Italy","Ikorodu, Nigeria","Nala Sopara, India","Little Rock (AR), United States","Milton Keynes, United Kingdom","Lille, France","Higashihiroshima, Japan","Silchar, India","Reggio di Calabria, Italy","Uppsala, Sweden","Sidi-bel-Abbès, Algeria","Balashikha, Russia","Saarbrücken, Germany","Kutaisi, Georgia","Kodaira, Japan","Durán, Ecuador","Kyzylorda, Kazakhstan","Oxnard (CA), United States","Kamensk-Uralsky, Russia","Neuquén, Argentina","Machilipatnam, India","Donostia - San Sebastián, Spain","Rewa, India","Kut, Iraq","Mainz, Germany","Fergana, Uzbekistan","Amarillo (TX), United States","Sunderland, United Kingdom","Sambhal, India","Santander, Spain","Leganés, Spain","Bojnurd, Iran","Andong, South Korea","Pireas, Greece","Hamm, Germany","Petah Tiqwa, Israel","Narathiwat, Thailand","Araçatuba, Brazil","Kushiro, Japan","Syzran, Russia","St. John's, Canada","Dos Quebradas, Colombia","Ponce, Puerto Rico","Indaiatuba, Brazil","Manzhouli, China","Khomeini shahr, Iran","Miquan, China","Byatarayanapura, India","Yuzhno-Sakhalinsk, Russia","Asan, South Korea","Yachiyo, Japan","Khimki, Russia","Saint-Étienne, France","Modena, Italy","Antsirabe, Madagascar","Crawley, United Kingdom","Knoxville (TN), United States","San Salvador de Jujuy, Argentina","Newport News (VA), United States","Icheon, South Korea","Cotia, Brazil","Tagum, Philippines","Bacau, Romania","Podolsk, Russia","Nossa Senhora do Socorro, Brazil","Ube, Japan","Chapra, India","Novocherkassk, Russia","Envigado, Colombia","Tacloban, Philippines","Aletai, China","Almere, Netherlands","Yingtan, China","Moreno Valley (CA), United States","Iquique, Chile","Nova Friburgo, Brazil","Salt Lake City (UT), United States","Hyesan, North Korea","Jackson (MS), United States","Botshabelo, South Africa","Izumi (Osaka), Japan","Herat, Afghanistan","Biskra, Algeria","Mitaka, Japan","Pasuruan, Indonesia","MANAMA, Bahrain","Lemesos, Cyprus","Providence (RI), United States","Bielsko-Biala, Poland","Jessore, Bangladesh","North Las Vegas (NV), United States","Hino, Japan","Ferraz de Vasconcelos, Brazil","Bharuch, India","Mangaung, South Africa","Parma, Italy","Puerto Cabello, Venezuela","Los Teques, Venezuela","Bulandshahr, India","Riohacha, Colombia","Barra Mansa, Brazil","Puerto Montt, Chile","Kütahya, Turkey","Worcester (MA), United States","Sobral, Brazil","Atirau, Kazakhstan","Herne, Germany","Maikop, Russia","Takoradi, Ghana","Malolos, Philippines","Nueva San Salvador, El Salvador","Turku, Finland","Sullana, Peru","Raiganj, India","La Serena, Chile","Malkajgiri, India","Amadora, Portugal","Kragujevac, Serbia","Olsztyn, Poland","Vasai, India","Phusro, India","Chlef (Ech Cheliff), Algeria","Gilbert (AZ), United States","Imabari, Japan","Corum, Turkey","Mülheim an der Ruhr, Germany","Mangora, Pakistan","Xilin'haote, China","Bidar, India","Burgos, Spain","Ibirité, Brazil","Kosti, Sudan","Miskolc, Hungary","Chapecó, Brazil","Arica, Chile","Hirosaki, Japan","Kaliningrad (Moskovskaya oblast), Russia","Bukand, Iran","Kottayam, India","Renfrewshire, United Kingdom","Tomakomai, Japan","Ontario (CA), United States","Netanya, Israel","Tachikawa, Japan","Chiniot, Pakistan","Cabo de Santo Agostinho, Brazil","Castellón de la Plana, Spain","Khandwa, India","Nakhodka, Russia","Pointe-à-Pitre, Guadeloupe","Beni-Suef, Egypt","Namdinh, Viet Nam","Bat Dambang, Cambodia","Alexandra, South Africa","Sakura, Japan","Kamakura, Japan","Chimoio, Mozambique","Iseyin, Nigeria","Tarija, Bolivia","Iwata, Japan","Haldia, India","Temirtau, Kazakhstan","Francisco Morato, Brazil","Obihiro, Japan","Volgodonsk, Russia","Mutare, Zimbabwe","Luque, Paraguay","Sohag, Egypt","Madiun, Indonesia","Kabwe, Zambia","Malappuram, India","Baharampur, India","Anjo, Japan","Pitesti, Romania","Hugli-Chinsurah, India","Parnamirim, Brazil","Moratuwa, Sri Lanka","Rondonópolis, Brazil","Breda, Netherlands","Bhiwani, India","Rancho Cucamonga (CA), United States","Rae Bareli, India","Guarenas, Venezuela","Ambato, Ecuador","Malayer, Iran","Guarapuava, Brazil","EL AAIUN, Western Sahara","Matsusaka, Japan","Aguas Lindas de Goiás, Brazil","Patrai, Greece","Lages, Brazil","Bahraich, India","Qaem shahr, Iran","Hadano, Japan","Pathankot, India","Santa Clarita (CA), United States","Aurora (IL), United States","Itajaí, Brazil","Ussuriisk, Russia","Geoje, South Korea","Ambala, India","Arad, Romania","SUVA, Fiji","Coquimbo, Chile","Baranovichi, Belarus","Bidhan Nagar, India","Miass, Russia","Takaoka, Japan","Berezniki, Russia","Brownsville (TX), United States","Fort Lauderdale (FL), United States","Ishinomaki, Japan","Coro, Venezuela","Khoy, Iran","Chirala, India","Wigan, United Kingdom","Biratnagar, Nepal","Holon, Israel","Comilla, Bangladesh","Huntsville (AL), United States","Oceanside (CA), United States","Mango, India","Garden Grove (CA), United States","Palangkaraya, Indonesia","Hebron, Palestine, Occupied Territory","Aktau, Kazakhstan","Amersfoort, Netherlands","Geelong, Australia","Al-Khubar, Saudi Arabia","Cabo Frio, Brazil","Solingen, Germany","Qarchak, Iran","Fianarantsoa, Madagascar","Tsu, Japan","Chingola, Zambia","Proddatur, India","Amroha, India","Overland Park (KS), United States","Sherbrooke, Canada","Alcorcón, Spain","Tongjiang, China","Osnabrück, Germany","Alor Setar, Malaysia","Corlu, Turkey","Germiston, South Africa","Szeged, Hungary","Ciudad Delgado, El Salvador","Chardzhou, Turkmenistan","Tumaco, Colombia","Fontana (CA), United States","Cotabato, Philippines","Ludwigshafen am Rhein, Germany","Sultan Pur Majra, India","Gombe, Nigeria","Abakan, Russia","Ålborg, Denmark","Qui Nhon, Viet Nam","Springs, South Africa","Hospet, India","Rzeszów, Poland","Gondar, Ethiopia","Bitung, Indonesia","Lalitpur, Nepal","Plzen, Czech Republic","Mytishchi, Russia","Itapecerica da Serra, Brazil","Chandan Nagar, India","Sudbury, Canada","Puerto Princesa, Philippines","Abbotsford, Canada","Perugia, Italy","Ayacucho, Peru","Albacete, Spain","Roi Et, Thailand","Tempe (AZ), United States","Adoni, India","Leverkusen, Germany","Kumbakonam, India","Macae, Brazil","Salatiga, Indonesia","Toulon, France","Livorno, Italy","Ciudad Del Carmen, Mexico","Bhadravati, India","Kota Kinabalu, Malaysia","Trondheim, Norway","Oyama, Japan","Sirsa, India","Jaunpur, India","s-Hertogenbosch, Netherlands","Cagliari, Italy","Ashikaga, Japan","Salamanca, Spain","Kanchanaburi, Thailand","Jiayuguan, China","Nijmegen, Netherlands","Kapra, India","Melitopol, Ukraine","Haldwani-cum-Kathgodam, India","Effon-Alaiye, Nigeria","Dayton (OH), United States","Lyubertsy, Russia","Narashino, Japan","West Lothian, United Kingdom","Iskenderun, Turkey","El Djelfa, Algeria","Reggio nell'Emilia, Italy","Cuddalore, India","Tallahassee (FL), United States","Castanhal, Brazil","Pervouralsk, Russia","Nacala, Mozambique","Warrington, United Kingdom","Pangkal Pinang, Indonesia","Mansfield, United Kingdom","Sayama, Japan","Rubtsovsk, Russia","Dinajpur, Bangladesh","Isparta, Turkey","Veraval, India","Kawanishi, Japan","Tunja, Colombia","Zanzibar, Tanzania","Puri, India","Rousse, Bulgaria","Vancouver (WA), United States","Genhe, China","Owo, Nigeria","Legasp, Philippines","Robertson Pet, India","Talcahuano, Chile","Ngaoundéré, Cameroon","Shebin-El-Kom, Egypt","Sandakan, Malaysia","Salavat, Russia","Salalah, Oman","Portmore, Jamaica","Surendranagar Dudhrej, India","Pécs, Hungary","Getafe, Spain","Pokhara, Nepal","Baleshwar, India","Tlemcen (Tilimsen), Algeria","Nandyal, India","Ado-Ekiti, Nigeria","Itu, Brazil","Apeldoorn, Netherlands","Madhyamgram, India","Swindon, United Kingdom","Kena, Egypt","Maraqeh, Iran","Urayasu, Japan","Ruili, China","Kingston, Canada","Gadag-Betgeri, India","Bogra, Bangladesh","Chattanooga (TN), United States","Poços de Caldas, Brazil","Capiatá, Paraguay","Sibiu, Romania","Enschede, Netherlands","Tebessa, Algeria","Ormoc, Philippines","San Carlos (Pangasinan), Philippines","Oldenburg, Germany","Kirari Suleman Nagar, India","Kerch, Ukraine","Pomona (CA), United States","Bhind, India","Luxer, Egypt","Hitachinaka, Japan","Chhindwara, India","Foggia, Italy","Skikda, Algeria","Grenoble, France","Mutrah, Oman","Medinipur, India","Niiza, Japan","Santa Rosa (CA), United States","Karur, India","Leskovac, Serbia","Chillán, Chile","Chittoor, India","Fukang, China","Ongole, India","Aydin, Turkey","Rockford (IL), United States","Mbeya, Tanzania","Mahajanga, Madagascar","Nagareyama, Japan","Shunan, Japan","Kamoke, Pakistan","Nawabganj, Bangladesh","Quetzaltenango, Guatemala","Chicoutimi-Jonquière, Canada","Burewala, Pakistan","Enakievo (Yenakievo), Ukraine","Nong Bua Lam Phu, Thailand","Sitapur, India","Fatehpur, India","Springfield (MA), United States","Chaiyaphum, Thailand","Makurdi, Nigeria","Bhalswa Jahangir Pur, India","Angers, France","Kovrov, Russia","Noda, Japan","Ogaki, Japan","Teresópolis, Brazil","Morena, India","Serilingampalle, India","Nilópolis, Brazil","Bawshar, Oman","Bushehr, Iran","Pembroke Pines (FL), United States","Nangloi Jat, India","Camaragibe, Brazil","Springfield (MO), United States","Uttarpara Kotrung, India","Dijon, France","Quelimane, Mozambique","Ravenna, Italy","Sebha, Libya","Paterson (NJ), United States","Tenali, India","Burnley/Nelson, United Kingdom","Borisov, Belarus","Kabankalan, Philippines","Neuss, Germany","Margilan, Uzbekistan","Phetchaburi, Thailand","Hatay, Turkey","Yonago, Japan","Las Tunas, Cuba","Brest, France","Corona (CA), United States","Potosí, Bolivia","Siverek, Turkey","Tacheng, China","Townsville, Australia","Jequié, Brazil","Balti, Moldova","PORT LOUIS, Mauritius","Tiaert, Algeria","Salem (OR), United States","Krishnanagar, India","Iruma, Japan","Karawal Nagar, India","Salzburg, Austria","Saqez, Iran","Hoshiarpur, India","Budaun, India","Leninakan(Gyumzi), Armenia","Kolomna, Russia","Saint Louis, Senegal","Paranaguá, Brazil","Gimcheon, South Korea","Dumfries & Galloway, United Kingdom","Batala, India","Formosa, Argentina","Chanthaburi, Thailand","Moriguchi, Japan","Phetchabun, Thailand","Jhelum, Pakistan","Calbayog, Philippines","Komaki, Japan","Umuahia, Nigeria","Logroño, Spain","Shivapuri, India","Prachuap Khiri Khan, Thailand","Pésterion, Greece","Cartago, Costa Rica","Bene Beraq, Israel","Tirgu-Mures, Romania","Salinas (CA), United States","Izumo, Japan","Florencia (Caquetá), Colombia","Bayamo, Cuba","Subotica, Serbia","Alandur, India","Lauro de Freitas, Brazil","Timon, Brazil","Elektrostal, Russia","Ondo, Nigeria","Le Mans, France","Ruda Slaska, Poland","Tama, Japan","Salamanca, Mexico","Zenica, Bosnia and Herzegovina","Gorontalo, Indonesia","Jinggangshan, China","Huelva, Spain","Usak, Turkey","Belovo, Russia","Dundee, United Kingdom","Valsad, India","Hollywood (FL), United States","Hampton (VA), United States","Tanjung Balai, Indonesia","Copiapó, Chile","St. Gallen, Switzerland","Koga, Japan","Ar'ar, Saudi Arabia","Falkirk, United Kingdom","Ranaghat, India","Vungtau, Viet Nam","Quilpué, Chile","Ilopango, El Salvador","Higashimurayama, Japan","Unnao, India","Calama, Chile","Viransehir, Turkey","Parakou, Benin","Shimla, India","Eugene (OR), United States","Bejaïa, Algeria","Sadiqabad, Pakistan","Caxias, Brazil","Grand Prairie (TX), United States","Barrackpur, India","Kansas City (KS), United States","Kakamigahara, Japan","Angra dos Reis, Brazil","Rijeka, Croatia","Isahaya, Japan","Luanshya, Zambia","Pallavaram, India","Pasadena (TX), United States","Badajoz, Spain","Pindamonhangaba, Brazil","Pasadena (CA), United States","Rajnandgaon, India","Jecheon (Chechon), South Korea","Arnhem, Netherlands","Parnaíba, Brazil","Bragança Paulista, Brazil","Seosan, South Korea","Itapetininga, Brazil","Balurghat, India","Oxford, United Kingdom","Caguas, Puerto Rico","Huánuco, Peru","Trois-Rivières, Canada","Pagadian, Philippines","Khoramshahr, Iran","Cienfuegos, Cuba","Tsuruoka, Japan","Torrance (CA), United States","Ede, Nigeria","Ome, Japan","Osorno, Chile","Otaru, Japan","San Cristóbal de La Laguna, Spain","Kariya, Japan","Bheemavaram, India","Yavatmal, India","Cadiz, Philippines","Ilam, Iran","Damaturu, Nigeria","Al-Fasher, Sudan","Slough, United Kingdom","Almetievsk, Russia","Chirchik, Uzbekistan","Jimeta, Nigeria","Bago, Philippines","Syracuse (NY), United States","Ipswich, United Kingdom","Dessie, Ethiopia","Naperville (IL), United States","Moji-Guaçu, Brazil","Stara Zagora, Bulgaria","Aksaray, Turkey"]


